name: Test Coverage

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn test-coverage
      - uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
